{"name": "Возникновение ошибки при пропуске поля пароль для аутентификации", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected response: {'code': 400, 'message': 'Недостаточно данных для входа'}\nassert {'code': 400,...ых для входа'} == {'message': '...ых для входа'}\n  \n  Omitting 1 identical items, use -vv to show\n  Left contains 1 more item:\n  {'code': 400}\n  Use -v to get more diff", "trace": "self = <tests.test_authorization_courier.TestCourierLogin object at 0x00000231A067CD60>\nregister_new_courier = (<Response [201]>, {'firstName': 'zowtigfmqh', 'login': 'njufzxvlie', 'password': 'jinqcwgrca'}, 498809)\n\n    @allure.title('Возникновение ошибки при пропуске поля пароль для аутентификации')\n    @allure.description('Генерация карточки курьера, попытка аутентификации без заполнения поля пароль. Код ответа 400 Bad Request, тело ответа Недостаточно данных для входа')\n    def test_courier_login_empty_password(self, register_new_courier):\n        response, payload, courier_id = register_new_courier\n        login = payload['login']\n        password = ''\n    \n        payload = {\n            'login': login,\n            'password': password\n        }\n        response = requests.post(Urls.url_courier_login, data=payload)\n        assert response.status_code == 400, f\"Unexpected status code: {response.status_code}\"\n>       assert response.json() == {'message': 'Недостаточно данных для входа'}, f\"Unexpected response: {response.json()}\"\nE       AssertionError: Unexpected response: {'code': 400, 'message': 'Недостаточно данных для входа'}\nE       assert {'code': 400,...ых для входа'} == {'message': '...ых для входа'}\nE         \nE         Omitting 1 identical items, use -vv to show\nE         Left contains 1 more item:\nE         {'code': 400}\nE         Use -v to get more diff\n\ntests\\test_authorization_courier.py:57: AssertionError"}, "description": "Генерация карточки курьера, попытка аутентификации без заполнения поля пароль. Код ответа 400 Bad Request, тело ответа Недостаточно данных для входа", "start": 1744123449989, "stop": 1744123450086, "uuid": "41ca1da7-986a-4172-929f-ea1f15dc0fbe", "historyId": "6e662937284310e081d4db601b308fba", "testCaseId": "6e662937284310e081d4db601b308fba", "fullName": "tests.test_authorization_courier.TestCourierLogin#test_courier_login_empty_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authorization_courier"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-HIR29C3"}, {"name": "thread", "value": "5896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authorization_courier"}]}