{"name": "Возникновение ошибки аутентификации курьера при вводе некорректного логина", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected response: {'code': 404, 'message': 'Учетная запись не найдена'}\nassert {'code': 404,...ь не найдена'} == {'message': '...ь не найдена'}\n  \n  Omitting 1 identical items, use -vv to show\n  Left contains 1 more item:\n  {'code': 404}\n  Use -v to get more diff", "trace": "self = <tests.test_authorization_courier.TestCourierLogin object at 0x00000231A067D220>\nregister_new_courier = (<Response [201]>, {'firstName': 'rxuqqkslzi', 'login': 'idxyxmcoft', 'password': 'cbdgzktupc'}, 498810)\n\n    @allure.title('Возникновение ошибки аутентификации курьера при вводе некорректного логина')\n    @allure.description('Генерация карточки курьера, попытка аутентификации с некорректным логином. Код ответа 404 Not Found, тело ответа Учетная запись не найдена')\n    def test_courier_login_wrong_login(self, register_new_courier):\n        response, payload, courier_id = register_new_courier\n        login = generate_random_string(10)\n        password = payload['password']\n    \n        payload = {\n            'login': login,\n            'password': password\n        }\n        response = requests.post(Urls.url_courier_login, data=payload)\n        assert response.status_code == 404, f\"Unexpected status code: {response.status_code}\"\n>       assert response.json() == {'message': 'Учетная запись не найдена'}, f\"Unexpected response: {response.json()}\"\nE       AssertionError: Unexpected response: {'code': 404, 'message': 'Учетная запись не найдена'}\nE       assert {'code': 404,...ь не найдена'} == {'message': '...ь не найдена'}\nE         \nE         Omitting 1 identical items, use -vv to show\nE         Left contains 1 more item:\nE         {'code': 404}\nE         Use -v to get more diff\n\ntests\\test_authorization_courier.py:72: AssertionError"}, "description": "Генерация карточки курьера, попытка аутентификации с некорректным логином. Код ответа 404 Not Found, тело ответа Учетная запись не найдена", "start": 1744123450412, "stop": 1744123450502, "uuid": "6b4d8e37-7ace-43ab-b8a1-78f16519f258", "historyId": "27ff36af9f90a833c13b9a807b6c3c91", "testCaseId": "27ff36af9f90a833c13b9a807b6c3c91", "fullName": "tests.test_authorization_courier.TestCourierLogin#test_courier_login_wrong_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authorization_courier"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-HIR29C3"}, {"name": "thread", "value": "5896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authorization_courier"}]}